Name = "Pols Voice"
Category = "Enemy"
Version = 1
Notes = "Pols Voice enemy (weak to only arrows) from the Hylian Modding actor pack."
[[Render]]
    Regex = "...."
    Segment = 6
    Scale = 0.015
    Animation = 1
    Hirearchy = 1