Name = "ShockFungus"
Category = "Enemy"
Version = 1
Notes = "Custom midboss, gives Link a hard time to approach it at close range due its electrical field. Becomes stronger as the fight progresses. Weak to fire and ice arrows. You can choose whenever to play midboss music or not via params."
[[Render]]
    Regex = "...."
    Segment = 6
    Scale = 0.3
    Animation = 1
    Hirearchy = 1
[[Property]]
	Mask          = 0x000F
	Name          = "Type"
	Target        = "Var"
	Dropdown = [ [ 0, "Normal"],[ 1, "Midboss music on aggro"],[ 2, "Midboss music on aggro, 2x health"]]