Name = "Floor Spikes"
Category = "BG"
Version = 1
Notes = "Retractable floor spikes by hiisuya, from the Hylian Modding actor pack.\n\nThe types "Switch Start On/Off" will ALWAYS react to switch flags. They will override if you say not to.\nThere is an ON and OFF state which is controlled by Switch Flags for every type. If you don't allow Switch Flag reaction, then the state is always ON.\nAll types will maintain their ON/OFF position based on their parameters (and switch status) on room reload.\nAka: If a Cyclic Spike that reacts to Switch Flag has that flag set, it will retract and be turned OFF. It will then remain OFF unti\nthat flag is unset.\nIf you need to change timings, use the defines labeled below, though the results may not be perfect."

[[Render]]
    Regex = "...."
    Segment = 6
    Scale = 0.01
    DisplayList = "0x06000ba8,0x060022a8,0x06003b58,0x060016c0,0x06002f78,0x06004b90"
    IgnoreRotation = [1,0,1]
[[Property]]
	Mask          = 0xF000
	Name          = "Type"
	Target        = "Var"
	Dropdown = [ [ 0, "Player Triggered"],[ 1, "Cyclic"],[ 2, "Start On"],[ 3, "Start Off"]]
[[Property]]
	Mask          = 0x0F00
	Name          = "Size"
	Target        = "Var"
	Dropdown = [ [ 0, "Small"],[ 1, "Medium"],[ 2, "Large"]]
[[Property]]
    Mask          = 0x0001
    Name          = "React to Switch Flag"
    Target        = "XRot"
[[Property]]
    Mask          = 0x0001
    Name          = "Void out on touch"
    Target        = "ZRot"
[[Property]]
	Mask          = 0x00FF
	Name          = "Switch Flag"
	Target        = "Var"