Name = "BoB"
Category = "Enemy"
Version = 1

[[Render]]
    Regex = "...."
    Scale = 0.01
    Animation = 1
    YOffset = 20
[[Property]]
    Mask      = 0x003F
    Name      = "Switch Flag (Nullable)"
    Target    = "Var"