Name = "Eyegore"
Category = "Enemy"
Version = 1
Notes = "Enemy ported from Majora's Mask, the cyclops-like enemy guarding a bridge in the stone tower temple, shot a light arrow to its eye!"
[[Render]]
    Regex = "...."
    Segment = 6
    Scale = 0.015
    Animation = 1
    Hierarchy = 1