Name = "Switch Camera"
Category = "BG"
Version = 1
Notes = "The camera will temporarily switch to this actor's position and rotation when Switch Flag is turned on, adjust the time in properties"

[[Property]]
	Mask          = 0x003F
	Name          = "Switch Flag"
	Target        = "Var"

[[Property]]
	Mask          = 0x1000
	Name          = "Discovery Sound"
	Target        = "Var"

[[Property]]
	Mask          = 0x00FF
	Name          = "Time in 1/10th seconds"
	Target        = "ZRot"